# Generated by Django 4.2.7 on 2023-12-05 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_student_cv_file_student_profile_picture'),
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internships',
            name='accept_applications',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='internships',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='authentication.companyauth'),
        ),
    ]
