# Generated by Django 4.2.7 on 2023-12-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='student_cvs/'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='student_profile_pics/'),
        ),
    ]
